# Generated by Django 3.2.6 on 2022-01-14 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default=0, max_length=128)),
                ('currency', models.CharField(default='', max_length=128)),
                ('type', models.CharField(choices=[('credit_card', 'credit_card'), ('debit_card', 'debit_card')], default='', max_length=128)),
                ('status', models.CharField(choices=[('credit_card', 'credit_card'), ('debit_card', 'debit_card')], default='pending', max_length=128)),
                ('authorization_code', models.CharField(blank=True, max_length=128, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
