# Generated by Django 3.2.6 on 2021-08-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelMixin',
        ),
    ]
