# Generated by Django 3.2.6 on 2021-08-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='date_created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='date_updated',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_updated',
            new_name='updated_on',
        ),
    ]
