# Generated by Django 3.2.6 on 2022-01-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='seats',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
